site_name: RTHeter Documentation
site_description: A Simulator for Real-Time Scheduling on Heterogeneous Architectures
site_url: https://EHPCL.github.io/RTHeter

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    # - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.sections
    - content.tabs.link

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Introduction: introduction.md
  - Getting Started:
      - Installation: installation.md
      - Basic Usage: basic_usage.md
      - Advanced Usage: advanced_usage.md
  - Case Studies:
      - RL Scheduling (Synthetic): rl_synthetic.md
      - RL Scheduling (ViT): rl_vit.md
      - Scheduler Benchmarking: benchmark.md
  - API Reference: api.md
  - About: about.md

repo_url: https://github.com/EHPCL/RTHeter/
edit_uri: blob/main/docs/

plugins:
  - search
